# Database
db.File=jdbc:sqlite:storage\\Databases\\ZSEXOBOT.sqlite
db.User=usuario
db.Pass=secreta

# # Datafile
df.ExoMunision=storage\\DataFile\\ExoMunision.txt


# Logs
df.logFile=storage/Logs/ZSAppErrors.log

#Tracer
df.ExoTracer=storage/DataFile/ExoTracer.txt

# Resource
res.img.Main=/ZSInfrastructureComponent/resources/img/ZSMain.png
res.img.Logo=/ZSInfrastructureComponent/resources/img/ZSLogo.png
res.img.Splash=/ZSInfrastructureComponent/resources/img/ZSSplash.png
